[build]
builder = "NIXPACKS"
preBuildCommand = "npm install"
buildCommand = "npm run build"
nixpacksPlan = {"providers":["node"]}
buildEnvironment = "V2"
cache = false

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
